### ISSUE TITLE
Error when sending/receiving message and deploy within a minute

### ISSUE THREAD

**Issue by deblasioluca** [inUtil-info/whin2-contrib#5]
The receiver node goes nuts when I send/receive a message and do a new deploy in node red within 1 minute. The receiver node continues to through the following errors:

"[WHIN-Error] WebSocket was closed before the connection was established"
"[WHIN] Connection died"

Errors will keep throughing until the receiver node is deleted, flow newly deployed and node red restarted

**Comment by lu4t** [comment]
Hi, the receiver node will only work on paid subscriptions. In coming releases we will update its look and feel, so that you can turn it on/off... it will be off by default, and we will include a dialog remembering users that it should not be used if they're on a free plan.
I will leave this issue open till this feature is added.

**Comment by lu4t** [comment]
update to 0.0.9 to use the switch and turn on and off the whin receive node. It will not work on free subscriptions.
